In [8]:
# Import the modules
import numpy as np
import pandas as pd
from pathlib import Path
from sklearn.metrics import balanced_accuracy_score, confusion_matrix, classification_report

---

## Split the Data into Training and Testing Sets

### Step 1: Read the `lending_data.csv` data from the `Resources` folder into a Pandas DataFrame.

In [20]:
# Read the CSV file from the Resources folder into a Pandas DataFrame
Lending_df = pd.read_csv(
        Path("/Users/celinaespinosa/Desktop/credit-risk-classification/Resources/lending_data.csv")
)
# Review the DataFrame
Lending_df.head()


loan_size  interest_rate  borrower_income  debt_to_income  num_of_accounts   
0    10700.0          7.672            52800        0.431818                5  \
1     8400.0          6.692            43600        0.311927                3   
2     9000.0          6.963            46100        0.349241                3   
3    10700.0          7.664            52700        0.430740                5   
4    10800.0          7.698            53000        0.433962                5   

   derogatory_marks  total_debt  loan_status  
0                 1       22800            0  
1                 0       13600            0  
2                 0       16100            0  
3                 1       22700            0  
4                 1       23000            0

### Step 2: Create the labels set (`y`)  from the “loan_status” column, and then create the features (`X`) DataFrame from the remaining columns.

In [28]:
# Separate the data into labels and features

# Separate the y variable, the labels
y= Lending_df["loan_status"]

# Separate the X variable, the features
x= Lending_df.drop(columns=["loan_status"])

In [29]:
# Review the y variable Series
print (y)

0        0
1        0
2        0
3        0
4        0
        ..
77531    1
77532    1
77533    1
77534    1
77535    1
Name: loan_status, Length: 77536, dtype: int64


In [31]:
# Review the X variable DataFrame
print(x)

       loan_size  interest_rate  borrower_income  debt_to_income   
0        10700.0          7.672            52800        0.431818  \
1         8400.0          6.692            43600        0.311927   
2         9000.0          6.963            46100        0.349241   
3        10700.0          7.664            52700        0.430740   
4        10800.0          7.698            53000        0.433962   
...          ...            ...              ...             ...   
77531    19100.0         11.261            86600        0.653580   
77532    17700.0         10.662            80900        0.629172   
77533    17600.0         10.595            80300        0.626401   
77534    16300.0         10.068            75300        0.601594   
77535    15600.0          9.742            72300        0.585062   

       num_of_accounts  derogatory_marks  total_debt  
0                    5                 1       22800  
1                    3                 0       13600  
2                 

### Step 3: Check the balance of the labels variable (`y`) by using the `value_counts` function.

In [32]:
# Check the balance of our target values
label_balance = y.value_counts()
print(label_balance)

loan_status
0    75036
1     2500
Name: count, dtype: int64


### Step 4: Split the data into training and testing datasets by using `train_test_split`.

In [37]:
# Import the train_test_learn module
from sklearn.model_selection import train_test_split

# Split the data using train_test_split
# Assign a random_state of 1 to the function
x_train, x_test, y_train, y_test = train_test_split(x, y, random_state=1)

---

## Create a Logistic Regression Model with the Original Data

###  Step 1: Fit a logistic regression model by using the training data (`X_train` and `y_train`).

In [40]:
# Import the LogisticRegression module from SKLearn
from sklearn.linear_model import LogisticRegression

# Instantiate the Logistic Regression model
# Assign a random_state parameter of 1 to the model
model = LogisticRegression(random_state=1)

# Fit the model using training data
model.fit(x_train, y_train)

LogisticRegression(random_state=1)

### Step 2: Save the predictions on the testing data labels by using the testing feature data (`X_test`) and the fitted model.

In [42]:
# Make a prediction using the testing data
y_pred = model.predict(x_test)


### Step 3: Evaluate the model’s performance by doing the following:

* Calculate the accuracy score of the model.

* Generate a confusion matrix.

* Print the classification report.

In [44]:
# Print the balanced_accuracy score of the model
balanced_acc = balanced_accuracy_score(y_test, y_pred)
print(f"Balanced Accuracy Score: {balanced_acc:.2f}")

Balanced Accuracy Score: 0.95


In [45]:
# Generate a confusion matrix for the model
conf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(conf_matrix)

Confusion Matrix:
[[18663   102]
 [   56   563]]


In [46]:
# Print the classification report for the model
class_report = classification_report(y_test, y_pred)
print("Classification Report:")
print(class_report)

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.99      1.00     18765
           1       0.85      0.91      0.88       619

    accuracy                           0.99     19384
   macro avg       0.92      0.95      0.94     19384
weighted avg       0.99      0.99      0.99     19384



### Step 4: Answer the following question.

**Question:** How well does the logistic regression model predict both the `0` (healthy loan) and `1` (high-risk loan) labels?

**Answer:** 

Class 0 (Healthy Loan):

Precision: 1.00
Recall: 0.99
F1-score: 1.00

For class 0 (healthy loans), the model has high precision and recall, indicating that it predicts healthy loans accurately and rarely misclassifies them.

Class 1 (High-Risk Loan):

Precision: 0.85
Recall: 0.91
F1-score: 0.88

For class 1 (high-risk loans), the model has lower precision compared to class 0, meaning it might predict some healthy loans as high-risk loans. However, the recall is still relatively high, indicating that the model correctly identifies a good portion of the actual high-risk loans.

---

## Predict a Logistic Regression Model with Resampled Training Data

### Step 1: Use the `RandomOverSampler` module from the imbalanced-learn library to resample the data. Be sure to confirm that the labels have an equal number of data points. 

In [49]:
# Import the RandomOverSampler module form imbalanced-learn
from imblearn.over_sampling import RandomOverSampler

# Instantiate the random oversampler model
# # Assign a random_state parameter of 1 to the model
ros = RandomOverSampler(random_state=1)

# Fit the original training data to the random_oversampler model
x_resampled, y_resampled = ros.fit_resample(x_train, y_train)

In [50]:
# Count the distinct values of the resampled labels data
resampled_label_counts = y_resampled.value_counts()
print(resampled_label_counts)
!

loan_status
0    56271
1    56271
Name: count, dtype: int64


### Step 2: Use the `LogisticRegression` classifier and the resampled data to fit the model and make predictions.

In [51]:
# Instantiate the Logistic Regression model
# Assign a random_state parameter of 1 to the model
logreg_resampled = LogisticRegression(random_state=1)

# Fit the model using the resampled training data
logreg_resampled.fit(x_resampled, y_resampled)

# Make a prediction using the testing data
y_pred_resampled = logreg_resampled.predict(x_test)

In [59]:
#Review prediction results
# Review prediction results
print(f"Predictions using Resampled Model:\n{y_pred_resampled}")


Predictions using Resampled Model:
[0 0 0 ... 0 0 0]


### Step 3: Evaluate the model’s performance by doing the following:

* Calculate the accuracy score of the model.

* Generate a confusion matrix.

* Print the classification report.

In [60]:
# Print the balanced_accuracy score of the model 
balanced_acc_resampled = balanced_accuracy_score(y_test, y_pred_resampled)
print(f"Balanced Accuracy Score (Resampled): {balanced_acc_resampled:.2f}")

Balanced Accuracy Score (Resampled): 0.99


In [62]:
# Generate a confusion matrix for the model
confusion_matrix_resampled = confusion_matrix(y_test, y_pred_resampled)
print(confusion_matrix_resampled)

[[18649   116]
 [    4   615]]


In [64]:
# Print the classification report for the model
classification_report_resampled = classification_report(y_test, y_pred_resampled)

print(f"Classification Report (Resampled):\n{classification_report_resampled}")

Classification Report (Resampled):
              precision    recall  f1-score   support

           0       1.00      0.99      1.00     18765
           1       0.84      0.99      0.91       619

    accuracy                           0.99     19384
   macro avg       0.92      0.99      0.95     19384
weighted avg       0.99      0.99      0.99     19384



### Step 4: Answer the following question

**Question:** How well does the logistic regression model, fit with oversampled data, predict both the `0` (healthy loan) and `1` (high-risk loan) labels?

**Answer:** The logistic regression model fitted with oversampled data performs quite well in predicting both the "0" (healthy loan) and "1" (high-risk loan) labels. The classification report shows high precision, recall, and F1-score for both classes. Specifically, for the high-risk loan class (1), the model achieves a high precision of 0.84, indicating that when it predicts a high-risk loan, it's correct 84% of the time. The recall for this class is also high at 0.99, indicating that the model is capturing 99% of the actual high-risk loans. Overall, the model demonstrates strong predictive performance for both classes, making it effective at identifying high-risk loans while maintaining accuracy for healthy loans as well.

In [ ]:
Credit Risk Analysis Report :
    Overview:The purpose of this analysis is to develop and evaluate a machine learning model to assess the 
    creditworthiness of borrowers using historical lending activity data from a peer-to-peer lending services 
    company. The goal is to build a model that can effectively predict whether a loan is at high risk of 
    defaulting or not.
    
    Model Evaluation Metrics:
        •Accuracy Score: The accuracy of the model in predicting both healthy and high-risk loans.
        •Precision Score: The percentage of correctly predicted high-risk loans out of all predicted high-risk loans.
        •Recall Score: The percentage of correctly predicted high-risk loans out of all actual high-risk loans.
            
    Model Performance:
        •Accuracy Score: The original logistic regression model achieved an accuracy score of 0.99 on the testing data. 
            The resampled logistic regression model also achieved an accuracy score of 0.99.
        •Precision Score (High-Risk Loans):
            Original Model: 0.85
            Resampled Model: 0.84
        •Recall Score (High-Risk Loans):
            Original Model: 0.91
            Resampled Model: 0.99
                
    Summary and Recommendations: 
        Both the original and resampled logistic regression models exhibited outstanding performance in predicting credit risk. 
        Here are the key takeaways:
            
        Accuracy: Both models achieved a high accuracy of 0.99, indicating their ability to correctly predict the majority of loan statuses.
        Precision: The precision score for predicting high-risk loans is relatively high for both models. The original model achieved a precision 
            of 0.85, and the resampled model achieved a precision of 0.84. This means that when the models classify a loan as high risk, they are 
            correct about 84% to 85% of the time.
        Recall: The resampled model significantly outperformed the original model in terms of recall for high-risk loans. The original model achieved
            a recall of 0.91, while the resampled model achieved a remarkable recall of 0.99. This indicates that the resampled model can effectively 
            identify almost all actual high-risk loans.
    Given the excellent accuracy, precision, and recall scores achieved by both models, it is recommended that the company use the resampled logistic 
    regression model for assessing credit risk. The resampled model provides a more balanced performance by effectively capturing high-risk loans while 
    maintaining high precision for both classes. Its high recall score suggests it's reliable in identifying loans with a high risk of default, which 
    is crucial for mitigating potential losses. Therefore, the resampled logistic regression model is well-suited for practical use in the company's 
    credit assessment process.